FROM registry.access.redhat.com/ubi9/python-39

USER root

RUN dnf -y install git libpq postgresql python3 && dnf clean all

RUN pip3 install httpx psycopg psycopg_pool starlette sse_starlette uvicorn

ADD main.py /app/main.py
ADD static /app/static

WORKDIR /app
ENTRYPOINT ["python3", "main.py"]
